spring:
  application:
    name: basic-mgmt-system

  # 数据源配置
  datasource:
    url: jdbc:postgresql://localhost:5432/mgmt_db
    username: ${DB_USERNAME:mgmt_user}
    password: ${DB_PASSWORD:mgmt_password}
    driver-class-name: org.postgresql.Driver

    # HikariCP 连接池配置
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: create-drop  # 开发阶段使用，生产环境改为validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  # 开启JPA审计
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred

# Actuator健康检查配置
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

# 日志配置
logging:
  level:
    com.ynet.mgmt: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.jpa: DEBUG

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api