# 开发环境配置
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mgmt_db
    username: ${DB_USERNAME:mgmt_user}
    password: ${DB_PASSWORD:mgmt_password}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# 开发环境日志级别
logging:
  level:
    root: INFO
    com.ynet.mgmt: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE