# 生产环境配置
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mgmt_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

  jpa:
    hibernate:
      ddl-auto: validate  # 生产环境不自动创建表
    show-sql: false

# 生产环境日志级别
logging:
  level:
    root: WARN
    com.ynet.mgmt: INFO
    org.hibernate.SQL: WARN