# 开发环境配置
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:mgmt_db}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:mgmt_user}
    password: ${DB_PASSWORD:mgmt_password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Redis配置 - Docker环境
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

# Elasticsearch配置 - Docker环境
elasticsearch:
  uris:
    - ${ELASTICSEARCH_URI:http://localhost:9200}

# 开发环境日志级别
logging:
  level:
    root: INFO
    com.ynet.mgmt: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE