spring:
  application:
    name: basic-mgmt-system

  # 数据源配置
  datasource:
    url: jdbc:postgresql://localhost:5432/mgmt_db
    username: ${DB_USERNAME:mgmt_user}
    password: ${DB_PASSWORD:mgmt_password}
    driver-class-name: org.postgresql.Driver

    # HikariCP 连接池配置
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update  # 保持数据持久性，自动更新表结构
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  # 开启JPA审计
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
    # Redis配置
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# Elasticsearch配置
elasticsearch:
  uris:
    - ${ELASTICSEARCH_URI:http://localhost:9200}
  username: ${ELASTICSEARCH_USERNAME:}
  password: ${ELASTICSEARCH_PASSWORD:}
  api-key: ${ELASTICSEARCH_API_KEY:}
  connection-timeout: 30s
  read-timeout: 30s
  ssl-enabled: ${ELASTICSEARCH_SSL_ENABLED:false}
  ssl-fingerprint: ${ELASTICSEARCH_SSL_FINGERPRINT:}
  index:
    default-settings:
      number-of-shards: ${ELASTICSEARCH_DEFAULT_SHARDS:1}
      number-of-replicas: ${ELASTICSEARCH_DEFAULT_REPLICAS:0}
      refresh-interval: 1s

# Actuator健康检查配置
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

# 日志配置
logging:
  level:
    com.ynet.mgmt: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.jpa: DEBUG

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api

# JWT配置
jwt:
  secret: ${JWT_SECRET:your-very-secure-secret-key-here-at-least-256-bits-long-for-hs256-algorithm}
  access-token-expiration: 3600000  # 1 hour in milliseconds
  refresh-token-expiration: 2592000000  # 30 days in milliseconds
  issuer: deepSearch
  audience: deepSearch-users
  algorithm: HS256

