# 测试环境配置
spring:
  datasource:
    # 使用H2内存数据库进行测试，避免依赖外部PostgreSQL
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

# 测试环境日志配置
logging:
  level:
    com.ynet.mgmt: DEBUG
    org.hibernate.SQL: DEBUG